/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */


export interface paths {
  "/admin/orders": {
    /** List all orders (service / API key) */
    get: {
      responses: {
        /** @description OK */
        200: {
          content: {
            "application/json": {
              /** Format: date-time */
              created_at?: string;
              /**
               * Format: int64
               * @example 1
               */
              id?: number;
              items?: {
                  /**
                   * Format: int64
                   * @example 1
                   */
                  product_id?: number;
                  /** @example 2 */
                  quantity?: number;
                  /**
                   * Format: double
                   * @example 129.99
                   */
                  unit_price?: number;
                }[];
              /** @example ORD-2026-0001 */
              order_number?: string;
              /**
               * @description pending | paid | shipped | cancelled
               * @example paid
               */
              status?: string;
              /**
               * Format: double
               * @example 259.98
               */
              total?: number;
            };
          };
        };
        /** @description Invalid API key */
        401: {
          content: {
            "application/json": {
              /** @example 404 */
              code?: number;
              details?: string;
              /** @example not found */
              error?: string;
            };
          };
        };
      };
    };
  };
  "/audit/transactions/{txid}": {
    /**
     * Correlated audit trail for one transaction
     * @description Returns every data-change and third-party API-call that shared one request's transaction id.
     */
    get: {
      parameters: {
        path: {
          /** @description Transaction id (from X-Transaction-ID) */
          txid: string;
        };
      };
      responses: {
        /** @description OK */
        200: {
          content: {
            "application/json": {
              api_calls?: {
                  /** Format: date-time */
                  created_at?: string;
                  /** @example 6 */
                  duration_ms?: number;
                  /** @example /v1/charges */
                  endpoint?: string;
                  /** Format: int64 */
                  id?: number;
                  /** @example POST */
                  method?: string;
                  /** @example payment-gateway */
                  service?: string;
                  /** @example 200 */
                  status_code?: number;
                }[];
              data_changes?: ({
                  /**
                   * @description create|update|delete|soft_delete|restore
                   * @example create
                   */
                  action?: string;
                  /** Format: date-time */
                  created_at?: string;
                  /** @example 12 */
                  entity_id?: string;
                  /** @example orders */
                  entity_type?: string;
                  /** Format: int64 */
                  id?: number;
                  new_values?: {
                    [key: string]: unknown;
                  };
                  old_values?: {
                    [key: string]: unknown;
                  };
                  /** @example 42 */
                  user_id?: string;
                })[];
              /** @description counts per kind */
              summary?: {
                [key: string]: number;
              };
              /** @example 20260603T050002-... */
              transaction_id?: string;
            };
          };
        };
        /** @description Invalid API key */
        401: {
          content: {
            "application/json": {
              /** @example 404 */
              code?: number;
              details?: string;
              /** @example not found */
              error?: string;
            };
          };
        };
      };
    };
  };
  "/auth/login": {
    /** Login with email + password */
    post: {
      /** @description Credentials */
      requestBody: {
        content: {
          "application/json": {
            /**
             * Format: email
             * @example andrian@example.com
             */
            email: string;
            /** @example s3cret-pass */
            password: string;
          };
        };
      };
      responses: {
        /** @description OK */
        200: {
          content: {
            "application/json": {
              /**
               * @description Bearer token for subsequent requests
               * @example 42
               */
              token?: string;
              user?: {
                /** Format: email */
                email?: string;
                /**
                 * Format: int64
                 * @example 42
                 */
                id?: number;
                /** @example Andrian Prasetya */
                name?: string;
                /**
                 * @description customer | admin
                 * @example customer
                 */
                role?: string;
                /** Format: uuid */
                uuid?: string;
              };
            };
          };
        };
        /** @description Invalid credentials */
        401: {
          content: {
            "application/json": {
              /** @example 404 */
              code?: number;
              details?: string;
              /** @example not found */
              error?: string;
            };
          };
        };
      };
    };
  };
  "/auth/register": {
    /** Register a new customer */
    post: {
      /** @description Registration payload */
      requestBody: {
        content: {
          "application/json": {
            /**
             * Format: email
             * @example andrian@example.com
             */
            email: string;
            /**
             * @description Full name
             * @example Andrian Prasetya
             */
            name: string;
            /**
             * @description Min 6 chars
             * @example s3cret-pass
             */
            password: string;
          };
        };
      };
      responses: {
        /** @description Created */
        201: {
          content: {
            "application/json": {
              /**
               * @description Bearer token for subsequent requests
               * @example 42
               */
              token?: string;
              user?: {
                /** Format: email */
                email?: string;
                /**
                 * Format: int64
                 * @example 42
                 */
                id?: number;
                /** @example Andrian Prasetya */
                name?: string;
                /**
                 * @description customer | admin
                 * @example customer
                 */
                role?: string;
                /** Format: uuid */
                uuid?: string;
              };
            };
          };
        };
        /** @description Validation error */
        400: {
          content: {
            "application/json": {
              /** @example 404 */
              code?: number;
              details?: string;
              /** @example not found */
              error?: string;
            };
          };
        };
      };
    };
  };
  "/notifications": {
    /** List my unread in-app notifications */
    get: {
      responses: {
        /** @description OK */
        200: {
          content: {
            "application/json": {
              data?: {
                  /** @example We got your order ORD-2026-0001 */
                  body?: string;
                  /** Format: date-time */
                  created_at?: string;
                  data?: {
                    [key: string]: unknown;
                  };
                  /** @example abc123 */
                  id?: string;
                  /** @example false */
                  read?: boolean;
                  /** @example Order received */
                  title?: string;
                  /** @example order.placed */
                  type?: string;
                }[];
              /** @example 2 */
              unread?: number;
            };
          };
        };
        /** @description Unauthorized */
        401: {
          content: {
            "application/json": {
              /** @example 404 */
              code?: number;
              details?: string;
              /** @example not found */
              error?: string;
            };
          };
        };
      };
    };
  };
  "/notifications/read-all": {
    /** Mark all my notifications read */
    post: {
      responses: {
        /** @description OK */
        200: {
          content: {
            "application/json": {
              /** @example ok */
              message?: string;
            };
          };
        };
        /** @description Unauthorized */
        401: {
          content: {
            "application/json": {
              /** @example 404 */
              code?: number;
              details?: string;
              /** @example not found */
              error?: string;
            };
          };
        };
      };
    };
  };
  "/orders": {
    /** Place an order (nested items) */
    post: {
      /** @description Order with line items */
      requestBody: {
        content: {
          "application/json": {
            /** @description Order line items */
            items: {
                /**
                 * Format: int64
                 * @example 1
                 */
                product_id: number;
                /** @example 2 */
                quantity: number;
              }[];
            shipping_address?: {
              /** @example Jakarta */
              city?: string;
              /** @example ID */
              country?: string;
              /** @example Jl. Sudirman 1 */
              line1?: string;
              /** @example 10220 */
              postal_code?: string;
            };
          };
        };
      };
      responses: {
        /** @description Created */
        201: {
          content: {
            "application/json": {
              /** Format: date-time */
              created_at?: string;
              /**
               * Format: int64
               * @example 1
               */
              id?: number;
              items?: {
                  /**
                   * Format: int64
                   * @example 1
                   */
                  product_id?: number;
                  /** @example 2 */
                  quantity?: number;
                  /**
                   * Format: double
                   * @example 129.99
                   */
                  unit_price?: number;
                }[];
              /** @example ORD-2026-0001 */
              order_number?: string;
              /**
               * @description pending | paid | shipped | cancelled
               * @example paid
               */
              status?: string;
              /**
               * Format: double
               * @example 259.98
               */
              total?: number;
            };
          };
        };
        /** @description Bad request */
        400: {
          content: {
            "application/json": {
              /** @example 404 */
              code?: number;
              details?: string;
              /** @example not found */
              error?: string;
            };
          };
        };
        /** @description Unauthorized */
        401: {
          content: {
            "application/json": {
              /** @example 404 */
              code?: number;
              details?: string;
              /** @example not found */
              error?: string;
            };
          };
        };
      };
    };
  };
  "/orders/{id}": {
    /** Get an order by id */
    get: {
      parameters: {
        path: {
          /** @description Order id */
          id: string;
        };
      };
      responses: {
        /** @description OK */
        200: {
          content: {
            "application/json": {
              /** Format: date-time */
              created_at?: string;
              /**
               * Format: int64
               * @example 1
               */
              id?: number;
              items?: {
                  /**
                   * Format: int64
                   * @example 1
                   */
                  product_id?: number;
                  /** @example 2 */
                  quantity?: number;
                  /**
                   * Format: double
                   * @example 129.99
                   */
                  unit_price?: number;
                }[];
              /** @example ORD-2026-0001 */
              order_number?: string;
              /**
               * @description pending | paid | shipped | cancelled
               * @example paid
               */
              status?: string;
              /**
               * Format: double
               * @example 259.98
               */
              total?: number;
            };
          };
        };
        /** @description Not found */
        404: {
          content: {
            "application/json": {
              /** @example 404 */
              code?: number;
              details?: string;
              /** @example not found */
              error?: string;
            };
          };
        };
      };
    };
  };
  "/products": {
    /** List published products */
    get: {
      parameters: {
        query?: {
          /** @description Page size (default 20) */
          limit?: string;
          /** @description Page offset (default 0) */
          offset?: string;
          /** @description Include unpublished (true/false) */
          all?: string;
        };
        header?: {
          /** @description Optional client trace id */
          "X-Request-ID"?: string;
        };
      };
      responses: {
        /** @description OK */
        200: {
          content: {
            "application/json": {
              data?: {
                  barcode?: string;
                  /** Format: date-time */
                  created_at?: string;
                  details?: string;
                  /**
                   * Format: int64
                   * @example 1
                   */
                  id?: number;
                  /** @example Mechanical Keyboard */
                  name?: string;
                  /**
                   * Format: double
                   * @example 129.99
                   */
                  price?: number;
                  /** @example true */
                  published?: boolean;
                  /** @example KB-001 */
                  sku?: string;
                  /**
                   * Format: int64
                   * @example 50
                   */
                  stock?: number;
                  /** Format: uuid */
                  uuid?: string;
                }[];
              /**
               * Format: int64
               * @example 42
               */
              total?: number;
            };
          };
        };
      };
    };
    /** Create a product (admin) */
    post: {
      /** @description Product to create */
      requestBody: {
        content: {
          "application/json": {
            /** @example Hot-swappable, 75% */
            details?: string;
            /** @example Mechanical Keyboard */
            name: string;
            /**
             * Format: double
             * @example 129.99
             */
            price: number;
            /** @example true */
            published?: boolean;
            /** @example KB-001 */
            sku: string;
            /**
             * Format: int64
             * @example 50
             */
            stock?: number;
            /**
             * @description Free-form tags
             * @example mechanical
             */
            tags?: string[];
          };
        };
      };
      responses: {
        /** @description Created */
        201: {
          content: {
            "application/json": {
              barcode?: string;
              /** Format: date-time */
              created_at?: string;
              details?: string;
              /**
               * Format: int64
               * @example 1
               */
              id?: number;
              /** @example Mechanical Keyboard */
              name?: string;
              /**
               * Format: double
               * @example 129.99
               */
              price?: number;
              /** @example true */
              published?: boolean;
              /** @example KB-001 */
              sku?: string;
              /**
               * Format: int64
               * @example 50
               */
              stock?: number;
              /** Format: uuid */
              uuid?: string;
            };
          };
        };
        /** @description Unauthorized */
        401: {
          content: {
            "application/json": {
              /** @example 404 */
              code?: number;
              details?: string;
              /** @example not found */
              error?: string;
            };
          };
        };
        /** @description Forbidden (not admin) */
        403: {
          content: {
            "application/json": {
              /** @example 404 */
              code?: number;
              details?: string;
              /** @example not found */
              error?: string;
            };
          };
        };
      };
    };
  };
  "/products/{id}": {
    /** Get a product by id */
    get: {
      parameters: {
        path: {
          /** @description Product id */
          id: string;
        };
      };
      responses: {
        /** @description OK */
        200: {
          content: {
            "application/json": {
              barcode?: string;
              /** Format: date-time */
              created_at?: string;
              details?: string;
              /**
               * Format: int64
               * @example 1
               */
              id?: number;
              /** @example Mechanical Keyboard */
              name?: string;
              /**
               * Format: double
               * @example 129.99
               */
              price?: number;
              /** @example true */
              published?: boolean;
              /** @example KB-001 */
              sku?: string;
              /**
               * Format: int64
               * @example 50
               */
              stock?: number;
              /** Format: uuid */
              uuid?: string;
            };
          };
        };
        /** @description Not found */
        404: {
          content: {
            "application/json": {
              /** @example 404 */
              code?: number;
              details?: string;
              /** @example not found */
              error?: string;
            };
          };
        };
      };
    };
  };
  "/products/{id}/image": {
    /** Upload a product image (multipart) */
    post: {
      parameters: {
        path: {
          /** @description Product id */
          id: string;
        };
      };
      /** @description multipart/form-data with an 'image' file field */
      requestBody: {
        content: {
          "application/json": {
            /**
             * Format: binary
             * @description Image file
             */
            image?: string;
          };
        };
      };
      responses: {
        /** @description Uploaded */
        200: {
          content: {
            "application/json": {
              /** @example ok */
              message?: string;
            };
          };
        };
        /** @description Not found */
        404: {
          content: {
            "application/json": {
              /** @example 404 */
              code?: number;
              details?: string;
              /** @example not found */
              error?: string;
            };
          };
        };
      };
    };
  };
  "/showcase": {
    /**
     * Edge-type schema showcase
     * @description Exercises pointer / time.Time / slice-of-struct / nested / map / no-tag / enum / uuid / []byte.
     */
    get: {
      parameters: {
        query: {
          /** @description Required query param */
          filter: string;
        };
      };
      responses: {
        /** @description OK */
        200: {
          content: {
            "application/json": {
              /** @description no json tag -> field name used */
              Untagged?: string;
              /**
               * Format: uuid
               * @description uuid format hint
               */
              id?: string;
              /** @description slice of struct */
              items?: {
                  /**
                   * Format: int64
                   * @example 1
                   */
                  product_id?: number;
                  /** @example 2 */
                  quantity?: number;
                  /**
                   * Format: double
                   * @example 129.99
                   */
                  unit_price?: number;
                }[];
              /** @description map -> additionalProperties */
              meta?: {
                [key: string]: number;
              };
              /** @description pointer -> nullable-ish */
              optional?: string;
              /**
               * Format: byte
               * @description []byte -> string/byte
               */
              raw_payload?: string;
              /** @description nested struct */
              ship?: {
                /** @example Jakarta */
                city?: string;
                /** @example ID */
                country?: string;
                /** @example Jl. Sudirman 1 */
                line1?: string;
                /** @example 10220 */
                postal_code?: string;
              };
              /**
               * @description enum-ish; one of active|inactive
               * @example active
               */
              status: string;
              /** @example a */
              tags?: string[];
              /**
               * Format: date-time
               * @description time.Time -> string/date-time
               */
              when?: string;
            };
          };
        };
        /** @description Server error */
        500: {
          content: {
            "application/json": {
              /** @example 404 */
              code?: number;
              details?: string;
              /** @example not found */
              error?: string;
            };
          };
        };
      };
    };
  };
}

export type webhooks = Record<string, never>;

export interface components {
  schemas: never;
  responses: never;
  parameters: never;
  requestBodies: never;
  headers: never;
  pathItems: never;
}

export type $defs = Record<string, never>;

export type external = Record<string, never>;

export type operations = Record<string, never>;
